/*
 * $Id: Tone.java 25438 2008-11-04 11:18:55Z elsen-ch $
 * 
 */
package com.my.model;

import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;



/**
 * RbtSqlConf generated by hbm2java
 */
public class Tone implements  java.io.Serializable {

	// Fields
	private static final long serialVersionUID = 4916213624842772971L;
	private Integer id;
	private String productIdentifier;
	private String producer;
	private boolean deleted;
	private boolean purged;
	private boolean availableViaWeb;
	private boolean availableViaWap;
	private boolean availableViaSms;
	private boolean availableViaIvr;
	private boolean availableViaUssd;
	private boolean availableViaShop;
	private boolean availableViaCustCare;
	private boolean availableViaBatch;
	private boolean availableViaProvisioning;
	private boolean availableViaRbtCopy;
	private Date approvalActionDate;
	private String approvalActionBy;
	private int distributionRetries;
	private int purchasePeriod;
	private Date expiryDate;
	private String smsOrderCode;
	private Integer ivrOrderCode;
	private Integer ussdOrderCode;
	private int played;
	private Date firstDeletionAttempt;
	private Date lastDeletionAttempt;
	private int fileDeletionErrors;
	private Map<Language, ToneDetails> details = new HashMap<Language, ToneDetails>();
	private Set<ToneCategory> toneCategories = new HashSet<ToneCategory>();

	private int hashCode = Integer.MIN_VALUE;

	public String getApprovalActionBy() {
		return approvalActionBy;
	}

	public void setApprovalActionBy(String approvalActionBy) {
		this.approvalActionBy = approvalActionBy;
	}

	public Date getApprovalActionDate() {
		return approvalActionDate;
	}

	public void setApprovalActionDate(Date approvalActionDate) {
		this.approvalActionDate = approvalActionDate;
	}

	public boolean isAvailableViaIvr() {
		return availableViaIvr;
	}

	public void setAvailableViaIvr(boolean availableViaIvr) {
		this.availableViaIvr = availableViaIvr;
	}

	public boolean isAvailableViaUssd() {
		return availableViaUssd;
	}

	public void setAvailableViaUssd(boolean availableViaUssd) {
		this.availableViaUssd = availableViaUssd;
	}

	public boolean isAvailableViaSms() {
		return availableViaSms;
	}

	public void setAvailableViaSms(boolean availableViaSms) {
		this.availableViaSms = availableViaSms;
	}

	public boolean isAvailableViaWap() {
		return availableViaWap;
	}

	public void setAvailableViaWap(boolean availableViaWap) {
		this.availableViaWap = availableViaWap;
	}

	public boolean isAvailableViaWeb() {
		return availableViaWeb;
	}

	public void setAvailableViaWeb(boolean availableViaWeb) {
		this.availableViaWeb = availableViaWeb;
	}

	public boolean isAvailableViaBatch() {
		return availableViaBatch;
	}

	public void setAvailableViaBatch(boolean availableViaBatch) {
		this.availableViaBatch = availableViaBatch;
	}

	public boolean isAvailableViaCustCare() {
		return availableViaCustCare;
	}

	public void setAvailableViaCustCare(boolean availableViaCustCare) {
		this.availableViaCustCare = availableViaCustCare;
	}

	public boolean isAvailableViaProvisioning() {
		return availableViaProvisioning;
	}

	public void setAvailableViaProvisioning(boolean availableViaProvisioning) {
		this.availableViaProvisioning = availableViaProvisioning;
	}

	public boolean isAvailableViaShop() {
		return availableViaShop;
	}

	public void setAvailableViaShop(boolean availableViaShop) {
		this.availableViaShop = availableViaShop;
	}

	public Date getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIvrOrderCode() {
		return ivrOrderCode;
	}

	public void setIvrOrderCode(Integer ivrOrderCode) {
		this.ivrOrderCode = ivrOrderCode;
	}

	public Integer getUssdOrderCode() {
		return ussdOrderCode;
	}

	public void setUssdOrderCode(Integer ussdOrderCode) {
		this.ussdOrderCode = ussdOrderCode;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public int getPlayed() {
		return played;
	}

	public void setPlayed(int played) {
		this.played = played;
	}

	public Map<Language, ToneDetails> getDetails() {
		return details;
	}

	public void setDetails(Map<Language, ToneDetails> details) {
		this.details = details;
	}

	public String getProducer() {
		return producer;
	}

	public void setProducer(String producer) {
		this.producer = producer;
	}

	public String getProductIdentifier() {
		return productIdentifier;
	}

	public void setProductIdentifier(String productIdentifier) {
		this.productIdentifier = productIdentifier;
	}

	public int getPurchasePeriod() {
		return purchasePeriod;
	}

	public void setPurchasePeriod(int purchasePeriod) {
		this.purchasePeriod = purchasePeriod;
	}

	public String getSmsOrderCode() {
		return smsOrderCode;
	}

	public void setSmsOrderCode(String smsOrderCode) {
		this.smsOrderCode = smsOrderCode;
	}

	public Set<ToneCategory> getToneCategories() {
		return toneCategories;
	}

	public void setToneCategories(Set<ToneCategory> toneCategories) {
		this.toneCategories = toneCategories;
	}

	public int getDistributionRetries() {
		return distributionRetries;
	}

	public void setDistributionRetries(int distributionRetries) {
		this.distributionRetries = distributionRetries;
	}


	@Override
	public boolean equals (Object obj) {
		if (null == obj) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		if (!(obj instanceof Tone)) {
			return false;
		}
		final Tone tone = (Tone) obj;
		if (null == this.getId() || null == tone.getId()) {
			return false;
		}
		return this.getId().equals(tone.getId());
	}

	@Override
	public int hashCode () {
		if (Integer.MIN_VALUE == hashCode) {
			if (null == this.getId()) {
				return super.hashCode();
			}
			final String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
			hashCode = hashStr.hashCode();
		}
		return hashCode;
	}

	public boolean isAvailableViaRbtCopy() {
		return availableViaRbtCopy;
	}

	public void setAvailableViaRbtCopy(boolean availableViaRbtCopy) {
		this.availableViaRbtCopy = availableViaRbtCopy;
	}


	public Date getFirstDeletionAttempt() {
		return firstDeletionAttempt;
	}

	public void setFirstDeletionAttempt(Date firstDeletionAttempt) {
		this.firstDeletionAttempt = firstDeletionAttempt;
	}

	public Date getLastDeletionAttempt() {
		return lastDeletionAttempt;
	}

	public void setLastDeletionAttempt(Date lastDeletionAttempt) {
		this.lastDeletionAttempt = lastDeletionAttempt;
	}

	public int getFileDeletionErrors() {
		return fileDeletionErrors;
	}

	public void setFileDeletionErrors(int fileDeletionErrors) {
		this.fileDeletionErrors = fileDeletionErrors;
	}

	public boolean isPurged() {
		return purged;
	}

	public void setPurged(boolean purged) {
		this.purged = purged;
	}

	
}


